### PR TITLE
CancellationToken parameters must come last

### PR DESCRIPTION
**Pull request by alaatm**
This also aligns with latest MediatR version as of change: https://github.com/jbogard/MediatR/pull/772

### CODE REVIEW

**Comment by martinothamar** [comment]
Thanks for this! Will definitely get this merged, but I think I will complete 2.0 first since its in RC already, and include this in the 3.0 release. There are other changes in the pipeline as well so 3.0 should be pretty quick. I'll se about finishing 2.0 over the coming days

**Comment by IliasP91** [comment]
hi there, any update on this? do you need a hand maybe?

**Comment by martinothamar** [comment]
From my side - 2.0 and 2.1 has been released. Next step is 3.0 release which will include this change and a lot of others. There are some conflicts here now so they need to be resolved first, after that this can be included in a 3.0-preview pretty quickly.

**Comment by martinothamar** [comment]
I just rebased and pushed some additional fixes due to the rebase. Thanks for the PR! (and sorry for the delay 😄)

**Pull request merged**
